### ISSUE TITLE
Need help enabling the autocompleter in js file

### ISSUE THREAD

**Issue by Raug** [PUGX/PUGXAutoCompleterBundle#17]
Hi everyone,

I'm trying to install the PUGXAutoCompleterBundle on my website but i'm having troubles enabling it in the js file since i don't know what to reference in the urllist.

I've tried to do everything as close to the given example as possible so i wrote a getBookAction and a searchBookAction functions in my controller.
Trouble is i have no idea what to modify in this line :
$('#book').autocompleter({url_list: '/book_search', url_get: '/book_get/'}); 

PS : I don't know if it's linked but i couldn't find where to write the few twig lines before and i assumed so far that i could go without it. Maybe this is the source of my problem...

[{% for book in results -%}
    {{ {id: book.id, label: book.name, value: book.name}|json_encode|raw }}
    {%- if not loop.last %},{% endif -%}
{%- endfor %}]

Thanks in advance for any help you guys could give me.

Raug

**Comment by garak** [comment]
The javascript line needs to be modified with the URLs you created. This means you mean to setup somehow your routing and create at least that two routes.
The twig lines are meant for a template for the ``searchBookAction`` action.

**Comment by Raug** [comment]
Thanks for this quick answer Garak.
I was expecting something to do with routing.yml 
I'm gonna try to complete the installation on my own from now on.

Thanks again =)

**Comment by garak** [comment]
Feel free to close to issue (if you made it) or to ask for more help.

**Comment by Raug** [comment]
Unfortunately i'm still having troubles with this autocomplete thingy.

I'm gonna try and describe my problem as precisely as possible.

This is a symfony project so basically i got a js file where i'm using this line :

$('#book').autocompleter({url_list: '/book_search', url_get: '/book_get/'});

The urls are pointing to my main bundle root directory.
So basically they're pointing to Folder1 and my controller (where the get and search functions are defined) is in : Folder1/Controller/Controller.php

As soon as i write this line in my js file, the js file fails to load as if there was a syntax error.
I got the exact same symptoms when i forget a comma or something like that.

Concerning the twig templates, i've created a twig file name searchBook.html.twig containing the twig lines from the documentation but i still don't know where to reference it.

I'll keep working on it but any help you can give me is welcome.

Raug

**Comment by garak** [comment]
I'm afraid you're not comfortable with the concept of route, template, and controller. Is this your first project with Symfony? If so, my advice is to look deeply in Symfony documentation, since ignoring such basic concepts is a big no-no. A possible alternative is getting help from an experienced developer (or even a mentoring)

**Comment by Raug** [comment]
This is indeed the first project, but so far i've had no problems creating new routes and functions in the controller assoociated with those routes but i'm a little confused with this js line that keeps messing the whole js file as if it was mispelled.

As for the template, i usually use those as return values in controller functions and since both searchBookAction and getBookAction both already have return values i can't find where they should be referenced.

I'll still keep digging and searching on my own.
Hopefully i'l be able to understand what's wrong.
