### ISSUE TITLE
findLikeName($q) in function searchBookAction() is custom query

### ISSUE THREAD

**Issue by shayster01** [PUGX/PUGXAutoCompleterBundle#22]
findLikeName($q) is not a standard query and should be included instructions

**Comment by giorgionetg** [comment]
But I think it is clear...

Here, a possible findLikeName repository method is used, to search with LIKE statement (e.g. "pe" will find "War and Peace").

"A possible findLikeName" is meaning you have to write your custom search Method in Repository!
