### ISSUE TITLE
Twitter bootstrap toogle issue

### ISSUE THREAD

**Issue by severin-bruhat** [PUGX/PUGXAutoCompleterBundle#23]
Hi, 

This bundle works find, but I'm having a problem with my navbar since I've installed it.
Here is my javascript inclusion in my main layout (juste before </body>) : 
```
{% javascripts 'bundles/myBundle/js/*' '@PUGXAutocompleterBundle/Resources/public/js/autocompleter-jqueryui.js' %}
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <script type="text/javascript" src="{{ asset_url }}"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  {% endjavascripts %}
```
and here is my toggle nav : 
```
                  <ul class="nav navbar-nav pull-right">
                      <li class="dropdown pull-right">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                ME
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                          <li><a href="#">link 1</a></li>
                          <li><a href="#">link 2</a></li>
                        </ul>
                      </li>
                  </ul>
```
I have no error in the console but the toggle doesn't work. And if I remove '@PUGXAutocompleterBundle/Resources/public/js/autocompleter-jqueryui.js'  from the javascript block, the toggle works, but of course, not the autocomplete....

As I have no error in the console, I don't really understand what is the problem... any idea ?

Thank you

**Comment by garak** [comment]
Try moving jquery and bootstrap before ``javascripts`` block.
Indeed, you should keep only the line with ``asset_url`` inside that block.

**Comment by severin-bruhat** [comment]
that works, thank you

**Comment by garak** [comment]
You're welcome
