### ISSUE TITLE
Avoid to load all the datas

### ISSUE THREAD

**Issue by ybensacq** [PUGX/PUGXAutoCompleterBundle#26]
I see that when I use AutocompleteType::Class for a field, doctrine load all the datas for the entity, could we avoid this? 

thank you

**Comment by garak** [comment]
Could you elaborate, please?

**Comment by ybensacq** [comment]
Hello, when I 
add this 

```php
    ->add('city', AutocompleteType::Class, array('required' => false, 'class' => 'AppBundle:GeoCity'))
```

I see in my symfony logs a query loading all the datas for my GeoCity entity.

Do you know what I mean ? 
Thx

**Comment by garak** [comment]
I'm sorry, but I'm not able to reproduce your issue.

**Comment by ybensacq** [comment]
Ok sorry you're right. We can close this issue. :)
