### ISSUE TITLE
Options "multiple" and "query_builder" don't exist

### ISSUE THREAD

**Issue by b519259** [PUGX/PUGXAutoCompleterBundle#32]
Hi.

I wanted to replace my "entity" type with PUGXAutocompleterType in a form, but OptionsResolver says that type doesn't support "multiple" (ManyToMany entity connection) or "query_builder" (standard for EntityType) options. Symfony 2.8, PUGXAutocompleter 1.2.
Any chances for support?

Regards.

**Comment by garak** [comment]
I'm afraid that supporting manyToMany is not trivial.
So: no, it's not supported nor planned to be supported.
If, anyway, you find a simple way to implement such feature, feel free to open a pull request.

About a "query_builder" option: it just doesn't make sense. This type is not an extension of entity type and retrieval of objects is up to you (see the docs).

Thank you
