### ISSUE TITLE
url_get not mandatory

### ISSUE THREAD

**Issue by bettinz** [PUGX/PUGXAutoCompleterBundle#37]
Hello, I can't figure what is the use of url_get.
Without this parameter everything works ok, but it return 2 errors (404)

I've a page with collection (an invoice with 'add a product'). The product name is an autocomplete.

If I complete the first row, and I click on 'add a product', it works but I see 2 404 error:
http://127.0.0.1:8000/invoices/1
http://127.0.0.1:8000/invoices/testprod

testprod is the name of the product, 1 is the ID of that product. 
http://127.0.0.1:8000/invoices/purchase

If in url_get i write '/product/' the 404 error became:
http://127.0.0.1:8000/product/1
http://127.0.0.1:8000/product/testprod

So I think it's related to url_get parameter

Thank you

**Comment by garak** [comment]
The value of `url_get` parameter must be the URL of the action where you retrieve your object. This is needed when the form is displayed in an "edit" state (as opposed to a "new" state), since the field must be filled with the current value

**Comment by bettinz** [comment]
Thank you for the help. How can I prevent the 404 errors since I'm in a "new" state?

**Comment by garak** [comment]
Just define your URL
