### ISSUE TITLE
Impossible to set specific ajax option without erase all of default ajax options

### ISSUE THREAD

**Issue by lasdou** [PUGX/PUGXAutoCompleterBundle#38]
Hi,

there is an issue in the autocompleter-select.js file which not allow to set specific ajax option.

at line 48

```
            if (settings.otherOptions) {
                $.extend(select2options, options.otherOptions);
            }
```
It will be more flexible to use the jQuery extend method in recursive mode like that

```
           if (settings.otherOptions) {
                $.extend(true, select2options, options.otherOptions);
            }
```
So on the initialisation of the autocompleter we can now set an ajax option like "quietMillis" or other options without erase all of the ajax options.

example 

```
var options = {
        url_list: 'http://myurl.com/list',
        url_get: 'http://myurl.com/get',
        placeholder: 'Type text',
        otherOptions: {            
            minimumInputLength: 3,
            formatNoMatches: 'No entry match.',
            formatSearching: 'wait please...',
            formatInputTooShort: 'not enough letters',
            ajax: {
                  quietMillis: 1000 // <-- my new parameter !!!
            }
        }
    };

$('#my_input').autocompleter(options);
```
thank you very much.

**Comment by lasdou** [comment]
Hi,
thanks for the commit, but you've not correct the good line, 

it's this one which cause the problem : 

```
if (settings.otherOptions) {
   $.extend(select2options, options.otherOptions);
}
```

**Comment by garak** [comment]
Sorry, my bad.
Do you think that the "deep" option is good also for `options`? I mean, should I revert the change or can I keep it? Other than correcting it on `otherOpentions`, of course

**Comment by lasdou** [comment]
On my side your changes hasn't made any bad effects. I was able to set others options like previously whithout any drawback or regression, you can keep the last commit and add a new one with the deep argument for the otherOptions.

Thank you very much.

Best regards.
