### ISSUE TITLE
cascade_validation

### ISSUE THREAD

**Issue by aczepod** [PUGX/PUGXAutoCompleterBundle#4]
aggiungendo al setDefaultOptions in un formType la codizione cascade_validation a true il form cerca di salvare nuovamente l'entità gestita dall'autocomplete generando errori a catena

**Comment by stephanvierkant** [comment]
English please?

**Comment by PixellCreativeSolutions** [comment]
If I set cascade_validation as true in setDefaultOptions on formType the entity managed by autocomplete try to save the entity again and again... This behaviour generate a errors cascade
