### ISSUE TITLE
Compatibility with Symfony 2.7

### ISSUE THREAD

**Issue by aureliengiry** [PUGX/PUGXAutoCompleterBundle#40]
Hi,

I detected an issue on your bundle with Symfony 2.7 (I'm on v2.7.20 on a project).
I have this exception 

> Could not load type "Symfony\Component\Form\Extension\Core\Type\TextType" 
> in vendor/symfony/symfony/src/Symfony/Component/Form/FormRegistry.php at line 83

After debug, I find issue on this file : **PUGXAutoCompleterBundle/Form/Type/AutocompleteType.php** method getParent()

```
    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return 'Symfony\Component\Form\Extension\Core\Type\TextType';
    }
```

After several searches on Symfony documention I found this : 

- for Symfony 2.7 we must have : http://symfony.com/doc/2.7/form/create_custom_field_type.html
```
public function getParent()
    {
        return 'choice';
    }
```
- Since Symfony 2.8 we must use complete namespace : http://symfony.com/doc/2.8/form/create_custom_field_type.html
```
public function getParent()
    {
        return ChoiceType::class;
    }
```

I don't test with SF 2.8 but your bundle version 1.2.6 was good for SF 2.7 : https://github.com/PUGX/PUGXAutoCompleterBundle/blob/v1.2.6/Form/Type/AutocompleteType.php#L67
And the code seems backwards compatible
```
 /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        // BC for Symfony < 3
        if (!method_exists('Symfony\Component\Form\AbstractType', 'getBlockPrefix')) {
            return 'text';
        }
        return 'Symfony\Component\Form\Extension\Core\Type\TextType';
    }

```
Because getBlockPrefix method exist in symfony 2.8, 3.0 and 3.1 :

- SF 2.7 : https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Form/AbstractType.php
- SF 2.8 : https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Form/AbstractType.php
- SF 3.0 : 
https://github.com/symfony/symfony/blob/3.0/src/Symfony/Component/Form/AbstractType.php
- SF 3.1 : https://github.com/symfony/symfony/blob/3.1/src/Symfony/Component/Form/AbstractType.php

If you don't have any time I can made fix and pull request.

regards

**Comment by garak** [comment]
We're actually using complete namespace, and using `::class` is just a shortcut (we can also switch to it, being the minimum requirement currently at php 5.5).
What you're telling here is that we should use Choice instead of Text?

**Comment by garak** [comment]
Also, TextType is actually also in 2.7, see http://api.symfony.com/2.7/Symfony/Component/Form/Extension/Core/Type/TextType.html

**Comment by aureliengiry** [comment]
No, it's just exemple form SF documentation for syntax.

I think best way is (from your bundle version 1.2.6):
```
/**
* {@inheritdoc}
*/
public function getParent()
{
    // BC for Symfony < 3
    if (!method_exists('Symfony\Component\Form\AbstractType', 'getBlockPrefix')) {
        return 'text';
    }

    return 'Symfony\Component\Form\Extension\Core\Type\TextType';
}
```

or 

```
use Symfony\Component\HttpKernel\Kernel;
...
/**
* {@inheritdoc}
*/
public function getParent()
{
    // BC for Symfony < 2.8
    if (Kernel::VERSION_ID < 20800) {
        return 'text';
    }else{
	return 'Symfony\Component\Form\Extension\Core\Type\TextType';
    }
}
```
Like code in unitest

regards,

**Comment by aureliengiry** [comment]
Nice !
