### ISSUE TITLE
Edit form shows entity id instead of name

### ISSUE THREAD

**Issue by nzurita** [PUGX/PUGXAutoCompleterBundle#44]
After following documentation everything seems to work fine, I can type a "name" and autocomplete shows correct values, and when I choose an option, name is written on the field (see first image). 

![imagen](https://user-images.githubusercontent.com/921345/33020902-3958629a-ce00-11e7-897d-45092c20f00e.png)

The problem is when I edit the entity, the autocomplete field shows the id instead of the name (see second image)

![imagen](https://user-images.githubusercontent.com/921345/33020929-52f923b0-ce00-11e7-9581-9d9720367270.png)

Am I missing some option?

These are my controller methods:

    /**
     * Autocomplete query for clients, based on name
     *
     * @Route("/search/name/", name="client_search_name")
     * @Method("GET")
     */
    public function searchClientLikeNameAction(Request $request)
    {
        $q = $request->query->get('term'); // https://github.com/PUGX/PUGXAutoCompleterBundle/blob/master/Resources/doc/index.md
        $results = $this->getDoctrine()->getRepository('AppBundle:Client')->findLikeName($q);

        return $this->render('client/auto-complete.html.twig', ['results' => $results]);
    }

    /**
     * Autocomplete query for clients, based on name
     *
     * @Route("/get/", name="client_get")
     * @Method("GET")
     */
    public function getClientAction($id = null)
    {
        $client = $this->getDoctrine()->getRepository('AppBundle:Client')->find($id);

        return new Response($client->__toString());
    }

**Comment by garak** [comment]
What is the content of `$client->__toString()`?

**Comment by nzurita** [comment]
public function __toString()
    {
        return ($this->surnames) ? ($this->name . ' '. $this->surnames) : $this->name;
    }

**Comment by garak** [comment]
Did you check if the ajax actually called getClientAction?

**Comment by nzurita** [comment]
I'll need some days to check this, I'm in another task now, sorry

**Comment by nzurita** [comment]
Found the error source, it was in the route definition, I hadn't included the **{id}** var and was throwing an error:

    /**
     * Autocomplete query for clients, based on name
     *
     * @Route("/get/{id}", name="client_get")
     * @Method("GET")
     */
    public function getClientAction($id = null)
    {
        $this->get('logger')->info(sprintf("getClientAction %d", $id));

        $client = $this->getDoctrine()->getRepository('AppBundle:Client')->find($id);

        return new Response($client->__toString());
    }
