### ISSUE TITLE
Autocomplete doesn't respect executing environment

### ISSUE THREAD

**Issue by nzurita** [PUGX/PUGXAutoCompleterBundle#45]
When running app in DEV environment (app_dev.php) the bundle calls search routes without `app_dev.php` prefix, this leads to some problems, one of them being necessary to delete cache for each modification, also can lead to session problems as (I think) sessions are independent in different environments.

**Comment by garak** [comment]
That part is up to you. You can easily make the javascript dynamic, using the current URL or retrieving URLs from the DOM

**Comment by nzurita** [comment]
Ok, you're right, I should have used `path` function instead of static url
