### ISSUE TITLE
No form validation is triggered when a value is entered but no option is selected from the list

### ISSUE THREAD

**Issue by joao66br** [PUGX/PUGXAutoCompleterBundle#50]
When the user types in some value in the field but doesn't select an option from the list, the form is not submitted but no validation message is displayed.
Thanks.

**Comment by garak** [comment]
That's a client-side problem: I guess that your field is required.
I'm afraid that such problem is outside the scope of this bundle

**Comment by garak** [comment]
If you use select2, there is `allowClear: true` option.

**Comment by miqwit** [comment]
Ha! great, thanks. However I use jQuery. I'll check if such an option exists as well.
