### ISSUE TITLE
How to make the autocomplete field required ?

### ISSUE THREAD

**Issue by vince83110** [PUGX/PUGXAutoCompleterBundle#55]
I use the simple configuration : 

```
->add('cli', AutocompleteType::class, [
          'label' => 'Le client*',
          'class' => TblClient::class,
         'required' => true
 ])
```

But the field is not required, I can let it empty and the user can submit the form. Is there something else to do ?

Thanks

**Comment by garak** [comment]
I'm afraid you need some client-side trick, e.g. something in javascript to add the `required` attribute to field, since the autocomplete field is not the same you're declaring in php/symfony

**Comment by vince83110** [comment]
But Select2JS relies on the required attribute of the field it replaces. Why this plugin doesn't allow this easily ? 

I tried this simple fiddle : http://jsfiddle.net/qsp3kgj8/

Only add required attribute to the input will work

**Comment by garak** [comment]
As mentioned in docs, this bundle does not support select2 version 4
