### ISSUE TITLE
Documentation overhaul

### ISSUE THREAD

**Issue by maathieu** [PUGX/PUGXAutoCompleterBundle#59]
For example, the script does not work without a proper stylesheet, but this is eluded by a single "Don't forget to include your stylesheet files." and no link to the said files...

Also, switching between jquery and select2 is not clear, as many changes need to be done manually in the code. Maybe a global section about why choosing one or the other would be helpful.

**Comment by garak** [comment]
Stylesheets are available on jquery-ui website and/or select2 website.

I'm not sure to understand your point on "switching", there's no switch, just pick one and use it. No need to change anything in bundle code.

**Comment by maathieu** [comment]
Thank you. I was wondering which one was better than the other, I managed to do my bidding using jquery-ui.
