### ISSUE TITLE
setting options when using jquery-ui

### ISSUE THREAD

**Issue by maathieu** [PUGX/PUGXAutoCompleterBundle#60]
Hi (again)!

The section "3.1 Select2 options" says how to add options to the autocompleter widget.

Some options also work using jquery-ui, the syntax is a little different however:

> var options = {
>     url_list: $('#url-list').attr('href'),
>     url_get: $('#url-get').attr('href'),
>
>     // for select2
>     // otherOptions: { 
>     //    minimumInputLength: 3,
>     // }
> 
>     // for jquery-ui
>     min_length: 3
> };
> $('#book_author').autocompleter(options);

Is it possible to either normalize the code so that setting options becomes independent from the library used, or document the way to set options for both libraries?

Many thanks in advance,

**Comment by garak** [comment]
It's already documented for both libraries, it isn't?

**Comment by maathieu** [comment]
The section 3.1 of the [documentation](https://github.com/PUGX/PUGXAutoCompleterBundle/blob/master/docs/index.md) only covers Select2 and jQuery-UI is not developed.
