### ISSUE TITLE
Avoid dependencies on javascript libraries

### ISSUE THREAD

**Issue by nzurita** [PUGX/PUGXAutoCompleterBundle#66]
As of 2020, this bundle offers 2 javascript libraries options:

* Select2, but not the last version 4.
* JQuery UI.

JqueryUI download page is now broken when using custom download. It has been like that for months (more than a year) and [they state it will take some more months](https://github.com/jquery/download.jqueryui.com/issues/390).

Using complete version of jqueryUI may confilct with some other plugins (that's my case) and using old version of Select2 also may lead to problems (I don't recall what exact problem I had but I couldn't use it either, maybe it forced to use an older version of some other library).

So, my question is: is there a built-in way to avoid using these libraries and implement my own? if not, do you plan to implement a built-in javascript list and avoid external dependencies? or at least... support last version of Select2?

Thank you.

**Comment by garak** [comment]
There are many different ways to use frontend assets in Symfony, so I can reply to your last question: no, I don't want to add frontend dependencies here.
My personal suggestion is to use [webpack encore](https://symfony.com/doc/current/frontend.html), combined with yarn or npm to declare your vendors (similarly to backend vendors declared with composer)

**Comment by nzurita** [comment]
You mean I should implement my own javascrpt solution and plug it to PUGX/AutoCompleterBundle with this utility?

**Comment by garak** [comment]
I did it like so in many projects.
No need to re-implement a solution, you can simply copy js files from here

**Comment by garak** [comment]
Solved with the new way of handling assets (via package.json)
