### ISSUE TITLE
Not working with symfony's webpack 1.0 and stimulus 2.0

### ISSUE THREAD

**Issue by ehymel** [PUGX/PUGXAutoCompleterBundle#70]
I have your bundle working with webpack 0.32 (using jquery-ui; had to add `import 'jquery-ui/ui/widgets/autocomplete';` to app.js to get it going).

When I update to the recently released webpack 1.0, your bundle no longer works.  I have no errors in my console. It looks like it does not start an async connection to fetch db results. 

I'm uncertain what the problem is or how to help you debug.

Any thoughts?

**Comment by garak** [comment]
I'm using this bundle with webpack encore myself and updated to version 1 without any problem.
You should be able to check assets compiling, checking that importing actually worked.

**Comment by ehymel** [comment]
OK thanks, I'll keep digging and report back if I figure out what's happening. Maybe it will help someone else!
